export const categories = {
  data: [
    {
      id: 1042,
      name: 'Beverages',
      nameAr: 'مشروبات',
      color: 'primary',
      companyId: 29,
      sequence: 0,
      branchCompanyCategories: [
        {
          id: 19,
          companyCategoryId: 1042,
          companyBranchId: 35,
          active: true,
        },
        {
          id: 54,
          companyCategoryId: 1042,
          companyBranchId: 36,
          active: true,
        },
        {
          id: 89,
          companyCategoryId: 1042,
          companyBranchId: 1037,
          active: true,
        },
        {
          id: 124,
          companyCategoryId: 1042,
          companyBranchId: 1043,
          active: true,
        },
        {
          id: 159,
          companyCategoryId: 1042,
          companyBranchId: 1044,
          active: true,
        },
        {
          id: 426,
          companyCategoryId: 1042,
          companyBranchId: 1078,
          active: true,
        },
      ],
    },
    {
      id: 1048,
      name: 'TT',
      nameAr: 'FF',
      color: 'primary',
      companyId: 29,
      sequence: 0,
      branchCompanyCategories: [
        {
          id: 25,
          companyCategoryId: 1048,
          companyBranchId: 35,
          active: true,
        },
        {
          id: 60,
          companyCategoryId: 1048,
          companyBranchId: 36,
          active: false,
        },
        {
          id: 95,
          companyCategoryId: 1048,
          companyBranchId: 1037,
          active: false,
        },
        {
          id: 130,
          companyCategoryId: 1048,
          companyBranchId: 1043,
          active: true,
        },
        {
          id: 165,
          companyCategoryId: 1048,
          companyBranchId: 1044,
          active: false,
        },
      ],
    },
    {
      id: 1049,
      name: 'category name',
      nameAr: 'cat name ar',
      color: 'primary',
      companyId: 29,
      sequence: 0,
      branchCompanyCategories: [
        {
          id: 26,
          companyCategoryId: 1049,
          companyBranchId: 35,
          active: true,
        },
        {
          id: 61,
          companyCategoryId: 1049,
          companyBranchId: 36,
          active: true,
        },
        {
          id: 96,
          companyCategoryId: 1049,
          companyBranchId: 1037,
          active: true,
        },
        {
          id: 131,
          companyCategoryId: 1049,
          companyBranchId: 1043,
          active: true,
        },
        {
          id: 166,
          companyCategoryId: 1049,
          companyBranchId: 1044,
          active: true,
        },
      ],
    },
    {
      id: 1068,
      name: 'category name',
      nameAr: 'category name',
      color: 'primary',
      companyId: 29,
      sequence: 0,
      branchCompanyCategories: [],
    },
    {
      id: 1069,
      name: 'Beverages',
      nameAr: 'Beverages',
      color: 'primary',
      companyId: 29,
      sequence: 0,
      branchCompanyCategories: [],
    },
    {
      id: 1070,
      name: 'Beverage 1',
      nameAr: 'مشروبات1',
      color: 'primary',
      companyId: 29,
      sequence: 0,
      branchCompanyCategories: [
        {
          id: 211,
          companyCategoryId: 1070,
          companyBranchId: 35,
          active: true,
        },
        {
          id: 212,
          companyCategoryId: 1070,
          companyBranchId: 36,
          active: true,
        },
        {
          id: 213,
          companyCategoryId: 1070,
          companyBranchId: 1037,
          active: true,
        },
        {
          id: 214,
          companyCategoryId: 1070,
          companyBranchId: 1043,
          active: true,
        },
        {
          id: 215,
          companyCategoryId: 1070,
          companyBranchId: 1044,
          active: true,
        },
      ],
    },
    {
      id: 1081,
      name: 'Retail',
      nameAr: 'منتجات البيع بالتجزئة',
      color: 'primary',
      companyId: 29,
      sequence: 0,
      branchCompanyCategories: [],
    },
    {
      id: 1107,
      name: 'Test Back',
      nameAr: 'تست باك',
      color: 'primary',
      companyId: 29,
      sequence: 0,
      branchCompanyCategories: [
        {
          id: 411,
          companyCategoryId: 1107,
          companyBranchId: 35,
          active: true,
        },
        {
          id: 412,
          companyCategoryId: 1107,
          companyBranchId: 36,
          active: true,
        },
        {
          id: 413,
          companyCategoryId: 1107,
          companyBranchId: 1037,
          active: false,
        },
        {
          id: 414,
          companyCategoryId: 1107,
          companyBranchId: 1043,
          active: true,
        },
        {
          id: 415,
          companyCategoryId: 1107,
          companyBranchId: 1044,
          active: true,
        },
        {
          id: 416,
          companyCategoryId: 1107,
          companyBranchId: 1064,
          active: false,
        },
        {
          id: 417,
          companyCategoryId: 1107,
          companyBranchId: 1065,
          active: false,
        },
      ],
    },
    {
      id: 1108,
      name: 'Project',
      nameAr: 'مشروع',
      color: 'primary',
      companyId: 29,
      sequence: 0,
      branchCompanyCategories: [
        {
          id: 418,
          companyCategoryId: 1108,
          companyBranchId: 35,
          active: false,
        },
        {
          id: 419,
          companyCategoryId: 1108,
          companyBranchId: 36,
          active: false,
        },
        {
          id: 420,
          companyCategoryId: 1108,
          companyBranchId: 1037,
          active: false,
        },
        {
          id: 421,
          companyCategoryId: 1108,
          companyBranchId: 1043,
          active: false,
        },
        {
          id: 422,
          companyCategoryId: 1108,
          companyBranchId: 1044,
          active: true,
        },
        {
          id: 423,
          companyCategoryId: 1108,
          companyBranchId: 1064,
          active: true,
        },
        {
          id: 424,
          companyCategoryId: 1108,
          companyBranchId: 1065,
          active: false,
        },
      ],
    },
    {
      id: 1079,
      name: 'xxx',
      nameAr: 'xxx',
      color: 'primary',
      companyId: 29,
      sequence: 1,
      branchCompanyCategories: [
        {
          id: 256,
          companyCategoryId: 1079,
          companyBranchId: 35,
          active: true,
        },
        {
          id: 257,
          companyCategoryId: 1079,
          companyBranchId: 36,
          active: true,
        },
        {
          id: 258,
          companyCategoryId: 1079,
          companyBranchId: 1037,
          active: false,
        },
        {
          id: 259,
          companyCategoryId: 1079,
          companyBranchId: 1043,
          active: false,
        },
        {
          id: 260,
          companyCategoryId: 1079,
          companyBranchId: 1044,
          active: false,
        },
      ],
    },
    {
      id: 1127,
      name: 'PIE',
      nameAr: 'الفطائر',
      color: 'primary',
      companyId: 29,
      sequence: 1,
      branchCompanyCategories: [
        {
          id: 532,
          companyCategoryId: 1127,
          companyBranchId: 1144,
          active: true,
        },
      ],
    },
    {
      id: 1033,
      name: 'Test Category1',
      nameAr: 'فئة تست1',
      color: 'pink',
      companyId: 29,
      sequence: 2,
      branchCompanyCategories: [
        {
          id: 12,
          companyCategoryId: 1033,
          companyBranchId: 35,
          active: true,
        },
        {
          id: 47,
          companyCategoryId: 1033,
          companyBranchId: 36,
          active: true,
        },
        {
          id: 82,
          companyCategoryId: 1033,
          companyBranchId: 1037,
          active: true,
        },
        {
          id: 117,
          companyCategoryId: 1033,
          companyBranchId: 1043,
          active: true,
        },
        {
          id: 152,
          companyCategoryId: 1033,
          companyBranchId: 1044,
          active: true,
        },
      ],
    },
    {
      id: 1128,
      name: 'PPQ',
      nameAr: 'مشاوي',
      color: 'danger',
      companyId: 29,
      sequence: 2,
      branchCompanyCategories: [
        {
          id: 533,
          companyCategoryId: 1128,
          companyBranchId: 1144,
          active: true,
        },
      ],
    },
    {
      id: 22,
      name: 'Roses',
      nameAr: 'الزهور',
      color: 'danger',
      companyId: 29,
      sequence: 3,
      branchCompanyCategories: [
        {
          id: 3,
          companyCategoryId: 22,
          companyBranchId: 35,
          active: true,
        },
        {
          id: 38,
          companyCategoryId: 22,
          companyBranchId: 36,
          active: true,
        },
        {
          id: 73,
          companyCategoryId: 22,
          companyBranchId: 1037,
          active: true,
        },
        {
          id: 108,
          companyCategoryId: 22,
          companyBranchId: 1043,
          active: true,
        },
        {
          id: 143,
          companyCategoryId: 22,
          companyBranchId: 1044,
          active: true,
        },
      ],
    },
    {
      id: 24,
      name: 'Perfumes',
      nameAr: 'العطور',
      color: 'secondary',
      companyId: 29,
      sequence: 4,
      branchCompanyCategories: [
        {
          id: 4,
          companyCategoryId: 24,
          companyBranchId: 35,
          active: true,
        },
        {
          id: 39,
          companyCategoryId: 24,
          companyBranchId: 36,
          active: true,
        },
        {
          id: 74,
          companyCategoryId: 24,
          companyBranchId: 1037,
          active: true,
        },
        {
          id: 109,
          companyCategoryId: 24,
          companyBranchId: 1043,
          active: true,
        },
        {
          id: 144,
          companyCategoryId: 24,
          companyBranchId: 1044,
          active: true,
        },
      ],
    },
    {
      id: 25,
      name: 'Super Market',
      nameAr: 'سوق مركزي',
      color: 'alternate',
      companyId: 29,
      sequence: 5,
      branchCompanyCategories: [
        {
          id: 5,
          companyCategoryId: 25,
          companyBranchId: 35,
          active: true,
        },
        {
          id: 40,
          companyCategoryId: 25,
          companyBranchId: 36,
          active: true,
        },
        {
          id: 75,
          companyCategoryId: 25,
          companyBranchId: 1037,
          active: true,
        },
        {
          id: 110,
          companyCategoryId: 25,
          companyBranchId: 1043,
          active: true,
        },
        {
          id: 145,
          companyCategoryId: 25,
          companyBranchId: 1044,
          active: true,
        },
        {
          id: 425,
          companyCategoryId: 25,
          companyBranchId: 1073,
          active: true,
        },
      ],
    },
    {
      id: 29,
      name: 'Bukhour',
      nameAr: 'البخور',
      color: 'pink',
      companyId: 29,
      sequence: 5,
      branchCompanyCategories: [
        {
          id: 9,
          companyCategoryId: 29,
          companyBranchId: 35,
          active: true,
        },
        {
          id: 44,
          companyCategoryId: 29,
          companyBranchId: 36,
          active: true,
        },
        {
          id: 79,
          companyCategoryId: 29,
          companyBranchId: 1037,
          active: true,
        },
        {
          id: 114,
          companyCategoryId: 29,
          companyBranchId: 1043,
          active: true,
        },
        {
          id: 149,
          companyCategoryId: 29,
          companyBranchId: 1044,
          active: true,
        },
      ],
    },
    {
      id: 27,
      name: 'Packing',
      nameAr: 'التغليف',
      color: 'danger',
      companyId: 29,
      sequence: 6,
      branchCompanyCategories: [
        {
          id: 7,
          companyCategoryId: 27,
          companyBranchId: 35,
          active: true,
        },
        {
          id: 42,
          companyCategoryId: 27,
          companyBranchId: 36,
          active: true,
        },
        {
          id: 77,
          companyCategoryId: 27,
          companyBranchId: 1037,
          active: true,
        },
        {
          id: 112,
          companyCategoryId: 27,
          companyBranchId: 1043,
          active: true,
        },
        {
          id: 147,
          companyCategoryId: 27,
          companyBranchId: 1044,
          active: true,
        },
      ],
    },
    {
      id: 1032,
      name: 'Saloon',
      nameAr: 'صالون نسائي',
      color: 'pink',
      companyId: 29,
      sequence: 6,
      branchCompanyCategories: [
        {
          id: 11,
          companyCategoryId: 1032,
          companyBranchId: 35,
          active: true,
        },
        {
          id: 46,
          companyCategoryId: 1032,
          companyBranchId: 36,
          active: true,
        },
        {
          id: 81,
          companyCategoryId: 1032,
          companyBranchId: 1037,
          active: true,
        },
        {
          id: 116,
          companyCategoryId: 1032,
          companyBranchId: 1043,
          active: true,
        },
        {
          id: 151,
          companyCategoryId: 1032,
          companyBranchId: 1044,
          active: true,
        },
      ],
    },
    {
      id: 1,
      name: 'Restaurants',
      nameAr: 'مطاعم',
      color: 'primary',
      companyId: 29,
      sequence: 7,
      branchCompanyCategories: [
        {
          id: 1,
          companyCategoryId: 1,
          companyBranchId: 35,
          active: true,
        },
        {
          id: 36,
          companyCategoryId: 1,
          companyBranchId: 36,
          active: true,
        },
        {
          id: 71,
          companyCategoryId: 1,
          companyBranchId: 1037,
          active: true,
        },
        {
          id: 106,
          companyCategoryId: 1,
          companyBranchId: 1043,
          active: true,
        },
        {
          id: 141,
          companyCategoryId: 1,
          companyBranchId: 1044,
          active: true,
        },
      ],
    },
    {
      id: 26,
      name: 'Gifts & Accessories',
      nameAr: 'هدايا واكسسوارات',
      color: 'info',
      companyId: 29,
      sequence: 8,
      branchCompanyCategories: [
        {
          id: 6,
          companyCategoryId: 26,
          companyBranchId: 35,
          active: true,
        },
        {
          id: 41,
          companyCategoryId: 26,
          companyBranchId: 36,
          active: true,
        },
        {
          id: 76,
          companyCategoryId: 26,
          companyBranchId: 1037,
          active: true,
        },
        {
          id: 111,
          companyCategoryId: 26,
          companyBranchId: 1043,
          active: true,
        },
        {
          id: 146,
          companyCategoryId: 26,
          companyBranchId: 1044,
          active: true,
        },
      ],
    },
    {
      id: 28,
      name: 'Pets Grooming  & Accessories',
      nameAr: 'خدمات ومستلزمات الحيوانات',
      color: 'info',
      companyId: 29,
      sequence: 8,
      branchCompanyCategories: [
        {
          id: 8,
          companyCategoryId: 28,
          companyBranchId: 35,
          active: true,
        },
        {
          id: 43,
          companyCategoryId: 28,
          companyBranchId: 36,
          active: true,
        },
        {
          id: 78,
          companyCategoryId: 28,
          companyBranchId: 1037,
          active: true,
        },
        {
          id: 113,
          companyCategoryId: 28,
          companyBranchId: 1043,
          active: true,
        },
        {
          id: 148,
          companyCategoryId: 28,
          companyBranchId: 1044,
          active: true,
        },
      ],
    },
    {
      id: 21,
      name: 'Productions  ',
      nameAr: 'الأنتاج',
      color: 'secondary',
      companyId: 29,
      sequence: 9,
      branchCompanyCategories: [
        {
          id: 2,
          companyCategoryId: 21,
          companyBranchId: 35,
          active: true,
        },
        {
          id: 37,
          companyCategoryId: 21,
          companyBranchId: 36,
          active: true,
        },
        {
          id: 72,
          companyCategoryId: 21,
          companyBranchId: 1037,
          active: true,
        },
        {
          id: 107,
          companyCategoryId: 21,
          companyBranchId: 1043,
          active: true,
        },
        {
          id: 142,
          companyCategoryId: 21,
          companyBranchId: 1044,
          active: true,
        },
      ],
    },
    {
      id: 1052,
      name: 'Orange Tea',
      nameAr: 'Orange Tea',
      color: 'primary',
      companyId: 29,
      sequence: 11,
      branchCompanyCategories: [
        {
          id: 28,
          companyCategoryId: 1052,
          companyBranchId: 35,
          active: true,
        },
        {
          id: 63,
          companyCategoryId: 1052,
          companyBranchId: 36,
          active: true,
        },
        {
          id: 98,
          companyCategoryId: 1052,
          companyBranchId: 1037,
          active: true,
        },
        {
          id: 133,
          companyCategoryId: 1052,
          companyBranchId: 1043,
          active: true,
        },
        {
          id: 168,
          companyCategoryId: 1052,
          companyBranchId: 1044,
          active: true,
        },
      ],
    },
    {
      id: 1059,
      name: 'Test Category',
      nameAr: 'فئة تست',
      color: 'danger',
      companyId: 29,
      sequence: 12,
      branchCompanyCategories: [
        {
          id: 35,
          companyCategoryId: 1059,
          companyBranchId: 35,
          active: true,
        },
        {
          id: 70,
          companyCategoryId: 1059,
          companyBranchId: 36,
          active: true,
        },
        {
          id: 105,
          companyCategoryId: 1059,
          companyBranchId: 1037,
          active: true,
        },
        {
          id: 140,
          companyCategoryId: 1059,
          companyBranchId: 1043,
          active: true,
        },
        {
          id: 175,
          companyCategoryId: 1059,
          companyBranchId: 1044,
          active: true,
        },
      ],
    },
    {
      id: 1037,
      name: 'تست مرتجعات',
      nameAr: 'تست مرتجعات',
      color: 'danger',
      companyId: 29,
      sequence: 14,
      branchCompanyCategories: [
        {
          id: 16,
          companyCategoryId: 1037,
          companyBranchId: 35,
          active: true,
        },
        {
          id: 51,
          companyCategoryId: 1037,
          companyBranchId: 36,
          active: true,
        },
        {
          id: 86,
          companyCategoryId: 1037,
          companyBranchId: 1037,
          active: true,
        },
        {
          id: 121,
          companyCategoryId: 1037,
          companyBranchId: 1043,
          active: true,
        },
        {
          id: 156,
          companyCategoryId: 1037,
          companyBranchId: 1044,
          active: true,
        },
      ],
    },
    {
      id: 1053,
      name: 'test cat',
      nameAr: 'test cat',
      color: 'primary',
      companyId: 29,
      sequence: 20,
      branchCompanyCategories: [
        {
          id: 29,
          companyCategoryId: 1053,
          companyBranchId: 35,
          active: false,
        },
        {
          id: 64,
          companyCategoryId: 1053,
          companyBranchId: 36,
          active: true,
        },
        {
          id: 99,
          companyCategoryId: 1053,
          companyBranchId: 1037,
          active: true,
        },
        {
          id: 134,
          companyCategoryId: 1053,
          companyBranchId: 1043,
          active: true,
        },
        {
          id: 169,
          companyCategoryId: 1053,
          companyBranchId: 1044,
          active: true,
        },
      ],
    },
    {
      id: 30,
      name: 'Paint & Tools',
      nameAr: 'اصباغ وادوات',
      color: 'warning',
      companyId: 29,
      sequence: 30,
      branchCompanyCategories: [
        {
          id: 10,
          companyCategoryId: 30,
          companyBranchId: 35,
          active: true,
        },
        {
          id: 45,
          companyCategoryId: 30,
          companyBranchId: 36,
          active: true,
        },
        {
          id: 80,
          companyCategoryId: 30,
          companyBranchId: 1037,
          active: true,
        },
        {
          id: 115,
          companyCategoryId: 30,
          companyBranchId: 1043,
          active: true,
        },
        {
          id: 150,
          companyCategoryId: 30,
          companyBranchId: 1044,
          active: true,
        },
      ],
    },
    {
      id: 1034,
      name: 'x',
      nameAr: 'x',
      color: 'danger',
      companyId: 29,
      sequence: 30,
      branchCompanyCategories: [
        {
          id: 13,
          companyCategoryId: 1034,
          companyBranchId: 35,
          active: true,
        },
        {
          id: 48,
          companyCategoryId: 1034,
          companyBranchId: 36,
          active: true,
        },
        {
          id: 83,
          companyCategoryId: 1034,
          companyBranchId: 1037,
          active: true,
        },
        {
          id: 118,
          companyCategoryId: 1034,
          companyBranchId: 1043,
          active: true,
        },
        {
          id: 153,
          companyCategoryId: 1034,
          companyBranchId: 1044,
          active: true,
        },
      ],
    },
    {
      id: 1036,
      name: 'Returns Test',
      nameAr: 'تست المرتجع',
      color: 'warning',
      companyId: 29,
      sequence: 30,
      branchCompanyCategories: [
        {
          id: 15,
          companyCategoryId: 1036,
          companyBranchId: 35,
          active: true,
        },
        {
          id: 50,
          companyCategoryId: 1036,
          companyBranchId: 36,
          active: true,
        },
        {
          id: 85,
          companyCategoryId: 1036,
          companyBranchId: 1037,
          active: true,
        },
        {
          id: 120,
          companyCategoryId: 1036,
          companyBranchId: 1043,
          active: true,
        },
        {
          id: 155,
          companyCategoryId: 1036,
          companyBranchId: 1044,
          active: true,
        },
      ],
    },
    {
      id: 1046,
      name: 'arabic',
      nameAr: 'arabic',
      color: 'primary',
      companyId: 29,
      sequence: 30,
      branchCompanyCategories: [
        {
          id: 23,
          companyCategoryId: 1046,
          companyBranchId: 35,
          active: true,
        },
        {
          id: 58,
          companyCategoryId: 1046,
          companyBranchId: 36,
          active: true,
        },
        {
          id: 93,
          companyCategoryId: 1046,
          companyBranchId: 1037,
          active: true,
        },
        {
          id: 128,
          companyCategoryId: 1046,
          companyBranchId: 1043,
          active: true,
        },
        {
          id: 163,
          companyCategoryId: 1046,
          companyBranchId: 1044,
          active: true,
        },
      ],
    },
    {
      id: 1055,
      name: 'Kuwait Category',
      nameAr: 'فئة فرع الكويت',
      color: 'danger',
      companyId: 29,
      sequence: 31,
      branchCompanyCategories: [
        {
          id: 31,
          companyCategoryId: 1055,
          companyBranchId: 35,
          active: true,
        },
        {
          id: 66,
          companyCategoryId: 1055,
          companyBranchId: 36,
          active: true,
        },
        {
          id: 101,
          companyCategoryId: 1055,
          companyBranchId: 1037,
          active: true,
        },
        {
          id: 136,
          companyCategoryId: 1055,
          companyBranchId: 1043,
          active: true,
        },
        {
          id: 171,
          companyCategoryId: 1055,
          companyBranchId: 1044,
          active: true,
        },
      ],
    },
    {
      id: 1056,
      name: ' Salmeya category',
      nameAr: 'فئة فرع السالمية',
      color: 'primary',
      companyId: 29,
      sequence: 32,
      branchCompanyCategories: [
        {
          id: 32,
          companyCategoryId: 1056,
          companyBranchId: 35,
          active: true,
        },
        {
          id: 67,
          companyCategoryId: 1056,
          companyBranchId: 36,
          active: true,
        },
        {
          id: 102,
          companyCategoryId: 1056,
          companyBranchId: 1037,
          active: true,
        },
        {
          id: 137,
          companyCategoryId: 1056,
          companyBranchId: 1043,
          active: true,
        },
        {
          id: 172,
          companyCategoryId: 1056,
          companyBranchId: 1044,
          active: true,
        },
      ],
    },
    {
      id: 1035,
      name: 'Category',
      nameAr: 'Category',
      color: 'warning',
      companyId: 29,
      sequence: 33,
      branchCompanyCategories: [
        {
          id: 14,
          companyCategoryId: 1035,
          companyBranchId: 35,
          active: true,
        },
        {
          id: 49,
          companyCategoryId: 1035,
          companyBranchId: 36,
          active: true,
        },
        {
          id: 84,
          companyCategoryId: 1035,
          companyBranchId: 1037,
          active: true,
        },
        {
          id: 119,
          companyCategoryId: 1035,
          companyBranchId: 1043,
          active: true,
        },
        {
          id: 154,
          companyCategoryId: 1035,
          companyBranchId: 1044,
          active: true,
        },
      ],
    },
    {
      id: 1060,
      name: 'cat1',
      nameAr: 'cat1',
      color: 'primary',
      companyId: 29,
      sequence: 33,
      branchCompanyCategories: [],
    },
    {
      id: 1063,
      name: 'category testo',
      nameAr: 'فئة اختبارو',
      color: 'danger',
      companyId: 29,
      sequence: 33,
      branchCompanyCategories: [
        {
          id: 186,
          companyCategoryId: 1063,
          companyBranchId: 35,
          active: true,
        },
        {
          id: 187,
          companyCategoryId: 1063,
          companyBranchId: 36,
          active: false,
        },
        {
          id: 188,
          companyCategoryId: 1063,
          companyBranchId: 1037,
          active: false,
        },
        {
          id: 189,
          companyCategoryId: 1063,
          companyBranchId: 1043,
          active: false,
        },
        {
          id: 190,
          companyCategoryId: 1063,
          companyBranchId: 1044,
          active: false,
        },
      ],
    },
    {
      id: 1083,
      name: 'Hallo',
      nameAr: 'Hallo',
      color: 'primary',
      companyId: 29,
      sequence: 34,
      branchCompanyCategories: [
        {
          id: 271,
          companyCategoryId: 1083,
          companyBranchId: 35,
          active: false,
        },
        {
          id: 272,
          companyCategoryId: 1083,
          companyBranchId: 36,
          active: false,
        },
        {
          id: 273,
          companyCategoryId: 1083,
          companyBranchId: 1037,
          active: false,
        },
        {
          id: 274,
          companyCategoryId: 1083,
          companyBranchId: 1043,
          active: false,
        },
        {
          id: 275,
          companyCategoryId: 1083,
          companyBranchId: 1044,
          active: true,
        },
      ],
    },
    {
      id: 1084,
      name: 'Snacks ',
      nameAr: 'مقرمشات ',
      color: 'primary',
      companyId: 29,
      sequence: 103,
      branchCompanyCategories: [
        {
          id: 276,
          companyCategoryId: 1084,
          companyBranchId: 35,
          active: false,
        },
        {
          id: 277,
          companyCategoryId: 1084,
          companyBranchId: 36,
          active: true,
        },
        {
          id: 278,
          companyCategoryId: 1084,
          companyBranchId: 1037,
          active: false,
        },
        {
          id: 279,
          companyCategoryId: 1084,
          companyBranchId: 1043,
          active: false,
        },
        {
          id: 280,
          companyCategoryId: 1084,
          companyBranchId: 1044,
          active: false,
        },
      ],
    },
    {
      id: 1085,
      name: 'Fruits Candy Rolls',
      nameAr: 'لفائف حلوى الفواكه ',
      color: 'primary',
      companyId: 29,
      sequence: 104,
      branchCompanyCategories: [
        {
          id: 281,
          companyCategoryId: 1085,
          companyBranchId: 35,
          active: false,
        },
        {
          id: 282,
          companyCategoryId: 1085,
          companyBranchId: 36,
          active: true,
        },
        {
          id: 283,
          companyCategoryId: 1085,
          companyBranchId: 1037,
          active: false,
        },
        {
          id: 284,
          companyCategoryId: 1085,
          companyBranchId: 1043,
          active: false,
        },
        {
          id: 285,
          companyCategoryId: 1085,
          companyBranchId: 1044,
          active: false,
        },
      ],
    },
    {
      id: 1086,
      name: 'WHITE MUSK',
      nameAr: 'مسك أبيض',
      color: 'primary',
      companyId: 29,
      sequence: 105,
      branchCompanyCategories: [
        {
          id: 286,
          companyCategoryId: 1086,
          companyBranchId: 35,
          active: false,
        },
        {
          id: 287,
          companyCategoryId: 1086,
          companyBranchId: 36,
          active: false,
        },
        {
          id: 288,
          companyCategoryId: 1086,
          companyBranchId: 1037,
          active: true,
        },
        {
          id: 289,
          companyCategoryId: 1086,
          companyBranchId: 1043,
          active: false,
        },
        {
          id: 290,
          companyCategoryId: 1086,
          companyBranchId: 1044,
          active: false,
        },
      ],
    },
    {
      id: 1087,
      name: 'Black MUSK',
      nameAr: 'مسك أسود',
      color: 'primary',
      companyId: 29,
      sequence: 106,
      branchCompanyCategories: [
        {
          id: 291,
          companyCategoryId: 1087,
          companyBranchId: 35,
          active: false,
        },
        {
          id: 292,
          companyCategoryId: 1087,
          companyBranchId: 36,
          active: false,
        },
        {
          id: 293,
          companyCategoryId: 1087,
          companyBranchId: 1037,
          active: true,
        },
        {
          id: 294,
          companyCategoryId: 1087,
          companyBranchId: 1043,
          active: false,
        },
        {
          id: 295,
          companyCategoryId: 1087,
          companyBranchId: 1044,
          active: false,
        },
      ],
    },
    {
      id: 1088,
      name: 'NATURAL OILS',
      nameAr: 'زيوت طبيعية',
      color: 'primary',
      companyId: 29,
      sequence: 107,
      branchCompanyCategories: [
        {
          id: 296,
          companyCategoryId: 1088,
          companyBranchId: 35,
          active: false,
        },
        {
          id: 297,
          companyCategoryId: 1088,
          companyBranchId: 36,
          active: false,
        },
        {
          id: 298,
          companyCategoryId: 1088,
          companyBranchId: 1037,
          active: true,
        },
        {
          id: 299,
          companyCategoryId: 1088,
          companyBranchId: 1043,
          active: false,
        },
        {
          id: 300,
          companyCategoryId: 1088,
          companyBranchId: 1044,
          active: false,
        },
      ],
    },
    {
      id: 1089,
      name: 'PERFUME OILS',
      nameAr: 'زيوت عطرية',
      color: 'primary',
      companyId: 29,
      sequence: 108,
      branchCompanyCategories: [
        {
          id: 301,
          companyCategoryId: 1089,
          companyBranchId: 35,
          active: false,
        },
        {
          id: 302,
          companyCategoryId: 1089,
          companyBranchId: 36,
          active: false,
        },
        {
          id: 303,
          companyCategoryId: 1089,
          companyBranchId: 1037,
          active: true,
        },
        {
          id: 304,
          companyCategoryId: 1089,
          companyBranchId: 1043,
          active: false,
        },
        {
          id: 305,
          companyCategoryId: 1089,
          companyBranchId: 1044,
          active: false,
        },
      ],
    },
    {
      id: 1090,
      name: 'NATURAL HONEY',
      nameAr: 'عسل طبيعي',
      color: 'primary',
      companyId: 29,
      sequence: 109,
      branchCompanyCategories: [
        {
          id: 306,
          companyCategoryId: 1090,
          companyBranchId: 35,
          active: false,
        },
        {
          id: 307,
          companyCategoryId: 1090,
          companyBranchId: 36,
          active: false,
        },
        {
          id: 308,
          companyCategoryId: 1090,
          companyBranchId: 1037,
          active: true,
        },
        {
          id: 309,
          companyCategoryId: 1090,
          companyBranchId: 1043,
          active: false,
        },
        {
          id: 310,
          companyCategoryId: 1090,
          companyBranchId: 1044,
          active: false,
        },
      ],
    },
    {
      id: 1091,
      name: 'OUD',
      nameAr: 'عود',
      color: 'primary',
      companyId: 29,
      sequence: 110,
      branchCompanyCategories: [
        {
          id: 311,
          companyCategoryId: 1091,
          companyBranchId: 35,
          active: false,
        },
        {
          id: 312,
          companyCategoryId: 1091,
          companyBranchId: 36,
          active: false,
        },
        {
          id: 313,
          companyCategoryId: 1091,
          companyBranchId: 1037,
          active: true,
        },
        {
          id: 314,
          companyCategoryId: 1091,
          companyBranchId: 1043,
          active: false,
        },
        {
          id: 315,
          companyCategoryId: 1091,
          companyBranchId: 1044,
          active: false,
        },
      ],
    },
    {
      id: 1092,
      name: 'AMBER',
      nameAr: 'عنبر',
      color: 'primary',
      companyId: 29,
      sequence: 111,
      branchCompanyCategories: [
        {
          id: 316,
          companyCategoryId: 1092,
          companyBranchId: 35,
          active: false,
        },
        {
          id: 317,
          companyCategoryId: 1092,
          companyBranchId: 36,
          active: false,
        },
        {
          id: 318,
          companyCategoryId: 1092,
          companyBranchId: 1037,
          active: true,
        },
        {
          id: 319,
          companyCategoryId: 1092,
          companyBranchId: 1043,
          active: false,
        },
        {
          id: 320,
          companyCategoryId: 1092,
          companyBranchId: 1044,
          active: false,
        },
      ],
    },
    {
      id: 1093,
      name: 'WARD',
      nameAr: 'ورد',
      color: 'primary',
      companyId: 29,
      sequence: 112,
      branchCompanyCategories: [
        {
          id: 321,
          companyCategoryId: 1093,
          companyBranchId: 35,
          active: false,
        },
        {
          id: 322,
          companyCategoryId: 1093,
          companyBranchId: 36,
          active: false,
        },
        {
          id: 323,
          companyCategoryId: 1093,
          companyBranchId: 1037,
          active: true,
        },
        {
          id: 324,
          companyCategoryId: 1093,
          companyBranchId: 1043,
          active: false,
        },
        {
          id: 325,
          companyCategoryId: 1093,
          companyBranchId: 1044,
          active: false,
        },
      ],
    },
    {
      id: 1094,
      name: 'BOKHOOR',
      nameAr: 'بخور',
      color: 'primary',
      companyId: 29,
      sequence: 113,
      branchCompanyCategories: [
        {
          id: 326,
          companyCategoryId: 1094,
          companyBranchId: 35,
          active: false,
        },
        {
          id: 327,
          companyCategoryId: 1094,
          companyBranchId: 36,
          active: false,
        },
        {
          id: 328,
          companyCategoryId: 1094,
          companyBranchId: 1037,
          active: true,
        },
        {
          id: 329,
          companyCategoryId: 1094,
          companyBranchId: 1043,
          active: false,
        },
        {
          id: 330,
          companyCategoryId: 1094,
          companyBranchId: 1044,
          active: false,
        },
      ],
    },
    {
      id: 1095,
      name: 'PERFUMES',
      nameAr: 'عطور',
      color: 'primary',
      companyId: 29,
      sequence: 114,
      branchCompanyCategories: [
        {
          id: 331,
          companyCategoryId: 1095,
          companyBranchId: 35,
          active: false,
        },
        {
          id: 332,
          companyCategoryId: 1095,
          companyBranchId: 36,
          active: false,
        },
        {
          id: 333,
          companyCategoryId: 1095,
          companyBranchId: 1037,
          active: true,
        },
        {
          id: 334,
          companyCategoryId: 1095,
          companyBranchId: 1043,
          active: false,
        },
        {
          id: 335,
          companyCategoryId: 1095,
          companyBranchId: 1044,
          active: false,
        },
      ],
    },
    {
      id: 1096,
      name: 'OTHERS',
      nameAr: 'أخرى',
      color: 'primary',
      companyId: 29,
      sequence: 115,
      branchCompanyCategories: [
        {
          id: 336,
          companyCategoryId: 1096,
          companyBranchId: 35,
          active: false,
        },
        {
          id: 337,
          companyCategoryId: 1096,
          companyBranchId: 36,
          active: false,
        },
        {
          id: 338,
          companyCategoryId: 1096,
          companyBranchId: 1037,
          active: true,
        },
        {
          id: 339,
          companyCategoryId: 1096,
          companyBranchId: 1043,
          active: false,
        },
        {
          id: 340,
          companyCategoryId: 1096,
          companyBranchId: 1044,
          active: false,
        },
      ],
    },
    {
      id: 1097,
      name: 'The main meals  الطـــــــبق الرئيسي ',
      nameAr: 'The main meals  الطـــــــبق الرئيسي ',
      color: 'primary',
      companyId: 29,
      sequence: 116,
      branchCompanyCategories: [
        {
          id: 341,
          companyCategoryId: 1097,
          companyBranchId: 35,
          active: false,
        },
        {
          id: 342,
          companyCategoryId: 1097,
          companyBranchId: 36,
          active: false,
        },
        {
          id: 343,
          companyCategoryId: 1097,
          companyBranchId: 1037,
          active: false,
        },
        {
          id: 344,
          companyCategoryId: 1097,
          companyBranchId: 1043,
          active: false,
        },
        {
          id: 345,
          companyCategoryId: 1097,
          companyBranchId: 1044,
          active: false,
        },
        {
          id: 346,
          companyCategoryId: 1097,
          companyBranchId: 1064,
          active: true,
        },
        {
          id: 347,
          companyCategoryId: 1097,
          companyBranchId: 1065,
          active: false,
        },
      ],
    },
    {
      id: 1098,
      name: 'Side Dishes الاطباق الجانبيــــــــــــة',
      nameAr: 'Side Dishes الاطباق الجانبيــــــــــــة',
      color: 'primary',
      companyId: 29,
      sequence: 117,
      branchCompanyCategories: [
        {
          id: 348,
          companyCategoryId: 1098,
          companyBranchId: 35,
          active: false,
        },
        {
          id: 349,
          companyCategoryId: 1098,
          companyBranchId: 36,
          active: false,
        },
        {
          id: 350,
          companyCategoryId: 1098,
          companyBranchId: 1037,
          active: false,
        },
        {
          id: 351,
          companyCategoryId: 1098,
          companyBranchId: 1043,
          active: false,
        },
        {
          id: 352,
          companyCategoryId: 1098,
          companyBranchId: 1044,
          active: false,
        },
        {
          id: 353,
          companyCategoryId: 1098,
          companyBranchId: 1064,
          active: true,
        },
        {
          id: 354,
          companyCategoryId: 1098,
          companyBranchId: 1065,
          active: false,
        },
      ],
    },
    {
      id: 1099,
      name: 'Hamsat الحمــــــــــــــــسات',
      nameAr: 'Hamsat الحمــــــــــــــــسات',
      color: 'primary',
      companyId: 29,
      sequence: 118,
      branchCompanyCategories: [
        {
          id: 355,
          companyCategoryId: 1099,
          companyBranchId: 35,
          active: false,
        },
        {
          id: 356,
          companyCategoryId: 1099,
          companyBranchId: 36,
          active: false,
        },
        {
          id: 357,
          companyCategoryId: 1099,
          companyBranchId: 1037,
          active: false,
        },
        {
          id: 358,
          companyCategoryId: 1099,
          companyBranchId: 1043,
          active: false,
        },
        {
          id: 359,
          companyCategoryId: 1099,
          companyBranchId: 1044,
          active: false,
        },
        {
          id: 360,
          companyCategoryId: 1099,
          companyBranchId: 1064,
          active: true,
        },
        {
          id: 361,
          companyCategoryId: 1099,
          companyBranchId: 1065,
          active: false,
        },
      ],
    },
    {
      id: 1100,
      name: 'Soup الشوربـــــــــة ',
      nameAr: 'Soup الشوربـــــــــة ',
      color: 'primary',
      companyId: 29,
      sequence: 119,
      branchCompanyCategories: [
        {
          id: 362,
          companyCategoryId: 1100,
          companyBranchId: 35,
          active: false,
        },
        {
          id: 363,
          companyCategoryId: 1100,
          companyBranchId: 36,
          active: false,
        },
        {
          id: 364,
          companyCategoryId: 1100,
          companyBranchId: 1037,
          active: false,
        },
        {
          id: 365,
          companyCategoryId: 1100,
          companyBranchId: 1043,
          active: false,
        },
        {
          id: 366,
          companyCategoryId: 1100,
          companyBranchId: 1044,
          active: false,
        },
        {
          id: 367,
          companyCategoryId: 1100,
          companyBranchId: 1064,
          active: true,
        },
        {
          id: 368,
          companyCategoryId: 1100,
          companyBranchId: 1065,
          active: false,
        },
      ],
    },
    {
      id: 1101,
      name: 'Appetizers المقبــــــــــــــــــــلات',
      nameAr: 'Appetizers المقبــــــــــــــــــــلات',
      color: 'primary',
      companyId: 29,
      sequence: 120,
      branchCompanyCategories: [
        {
          id: 369,
          companyCategoryId: 1101,
          companyBranchId: 35,
          active: false,
        },
        {
          id: 370,
          companyCategoryId: 1101,
          companyBranchId: 36,
          active: false,
        },
        {
          id: 371,
          companyCategoryId: 1101,
          companyBranchId: 1037,
          active: false,
        },
        {
          id: 372,
          companyCategoryId: 1101,
          companyBranchId: 1043,
          active: false,
        },
        {
          id: 373,
          companyCategoryId: 1101,
          companyBranchId: 1044,
          active: false,
        },
        {
          id: 374,
          companyCategoryId: 1101,
          companyBranchId: 1064,
          active: true,
        },
        {
          id: 375,
          companyCategoryId: 1101,
          companyBranchId: 1065,
          active: false,
        },
      ],
    },
    {
      id: 1102,
      name: 'Salads السلــــــــــــــطات',
      nameAr: 'Salads السلــــــــــــــطات',
      color: 'primary',
      companyId: 29,
      sequence: 121,
      branchCompanyCategories: [
        {
          id: 376,
          companyCategoryId: 1102,
          companyBranchId: 35,
          active: false,
        },
        {
          id: 377,
          companyCategoryId: 1102,
          companyBranchId: 36,
          active: false,
        },
        {
          id: 378,
          companyCategoryId: 1102,
          companyBranchId: 1037,
          active: false,
        },
        {
          id: 379,
          companyCategoryId: 1102,
          companyBranchId: 1043,
          active: false,
        },
        {
          id: 380,
          companyCategoryId: 1102,
          companyBranchId: 1044,
          active: false,
        },
        {
          id: 381,
          companyCategoryId: 1102,
          companyBranchId: 1064,
          active: true,
        },
        {
          id: 382,
          companyCategoryId: 1102,
          companyBranchId: 1065,
          active: false,
        },
      ],
    },
    {
      id: 1103,
      name: 'Maabeej المــــــــــــــــــعابيج ',
      nameAr: 'Maabeej المــــــــــــــــــعابيج ',
      color: 'primary',
      companyId: 29,
      sequence: 122,
      branchCompanyCategories: [
        {
          id: 383,
          companyCategoryId: 1103,
          companyBranchId: 35,
          active: false,
        },
        {
          id: 384,
          companyCategoryId: 1103,
          companyBranchId: 36,
          active: false,
        },
        {
          id: 385,
          companyCategoryId: 1103,
          companyBranchId: 1037,
          active: false,
        },
        {
          id: 386,
          companyCategoryId: 1103,
          companyBranchId: 1043,
          active: false,
        },
        {
          id: 387,
          companyCategoryId: 1103,
          companyBranchId: 1044,
          active: false,
        },
        {
          id: 388,
          companyCategoryId: 1103,
          companyBranchId: 1064,
          active: true,
        },
        {
          id: 389,
          companyCategoryId: 1103,
          companyBranchId: 1065,
          active: false,
        },
      ],
    },
    {
      id: 1104,
      name: 'Extras إضافــــــــــــــــــات',
      nameAr: 'Extras إضافــــــــــــــــــات',
      color: 'primary',
      companyId: 29,
      sequence: 123,
      branchCompanyCategories: [
        {
          id: 390,
          companyCategoryId: 1104,
          companyBranchId: 35,
          active: false,
        },
        {
          id: 391,
          companyCategoryId: 1104,
          companyBranchId: 36,
          active: false,
        },
        {
          id: 392,
          companyCategoryId: 1104,
          companyBranchId: 1037,
          active: false,
        },
        {
          id: 393,
          companyCategoryId: 1104,
          companyBranchId: 1043,
          active: false,
        },
        {
          id: 394,
          companyCategoryId: 1104,
          companyBranchId: 1044,
          active: false,
        },
        {
          id: 395,
          companyCategoryId: 1104,
          companyBranchId: 1064,
          active: true,
        },
        {
          id: 396,
          companyCategoryId: 1104,
          companyBranchId: 1065,
          active: false,
        },
      ],
    },
    {
      id: 1105,
      name: 'Drinks المشروبـــــــــــــات',
      nameAr: 'Drinks المشروبـــــــــــــات',
      color: 'primary',
      companyId: 29,
      sequence: 124,
      branchCompanyCategories: [
        {
          id: 397,
          companyCategoryId: 1105,
          companyBranchId: 35,
          active: false,
        },
        {
          id: 398,
          companyCategoryId: 1105,
          companyBranchId: 36,
          active: false,
        },
        {
          id: 399,
          companyCategoryId: 1105,
          companyBranchId: 1037,
          active: false,
        },
        {
          id: 400,
          companyCategoryId: 1105,
          companyBranchId: 1043,
          active: false,
        },
        {
          id: 401,
          companyCategoryId: 1105,
          companyBranchId: 1044,
          active: false,
        },
        {
          id: 402,
          companyCategoryId: 1105,
          companyBranchId: 1064,
          active: true,
        },
        {
          id: 403,
          companyCategoryId: 1105,
          companyBranchId: 1065,
          active: false,
        },
      ],
    },
    {
      id: 1106,
      name: 'Grills المــــــشــــــويـــــات',
      nameAr: 'Grills المــــــشــــــويـــــات',
      color: 'primary',
      companyId: 29,
      sequence: 125,
      branchCompanyCategories: [
        {
          id: 404,
          companyCategoryId: 1106,
          companyBranchId: 35,
          active: false,
        },
        {
          id: 405,
          companyCategoryId: 1106,
          companyBranchId: 36,
          active: false,
        },
        {
          id: 406,
          companyCategoryId: 1106,
          companyBranchId: 1037,
          active: false,
        },
        {
          id: 407,
          companyCategoryId: 1106,
          companyBranchId: 1043,
          active: false,
        },
        {
          id: 408,
          companyCategoryId: 1106,
          companyBranchId: 1044,
          active: false,
        },
        {
          id: 409,
          companyCategoryId: 1106,
          companyBranchId: 1064,
          active: true,
        },
        {
          id: 410,
          companyCategoryId: 1106,
          companyBranchId: 1065,
          active: false,
        },
      ],
    },
    {
      id: 1114,
      name: 'Main Category',
      nameAr: 'الفئة الرئيسية',
      color: 'primary',
      companyId: 29,
      sequence: 126,
      branchCompanyCategories: [
        {
          id: 470,
          companyCategoryId: 1114,
          companyBranchId: 1113,
          active: true,
        },
        {
          id: 503,
          companyCategoryId: 1114,
          companyBranchId: 1119,
          active: true,
        },
      ],
    },
    {
      id: 1115,
      name: 'قشرة الفواكه',
      nameAr: 'قشرة الفواكه',
      color: 'primary',
      companyId: 29,
      sequence: 127,
      branchCompanyCategories: [
        {
          id: 471,
          companyCategoryId: 1115,
          companyBranchId: 1113,
          active: true,
        },
      ],
    },
    {
      id: 1116,
      name: 'Healthy Sweets',
      nameAr: 'حلويات صحية',
      color: 'primary',
      companyId: 29,
      sequence: 128,
      branchCompanyCategories: [
        {
          id: 472,
          companyCategoryId: 1116,
          companyBranchId: 1113,
          active: true,
        },
        {
          id: 504,
          companyCategoryId: 1116,
          companyBranchId: 1119,
          active: true,
        },
      ],
    },
    {
      id: 1117,
      name: 'Hoodie',
      nameAr: 'Hoodie',
      color: 'primary',
      companyId: 29,
      sequence: 129,
      branchCompanyCategories: [
        {
          id: 473,
          companyCategoryId: 1117,
          companyBranchId: 1113,
          active: true,
        },
      ],
    },
    {
      id: 1118,
      name: 'Hoodie2',
      nameAr: 'Hoodie2',
      color: 'primary',
      companyId: 29,
      sequence: 130,
      branchCompanyCategories: [
        {
          id: 474,
          companyCategoryId: 1118,
          companyBranchId: 1113,
          active: true,
        },
      ],
    },
    {
      id: 1119,
      name: 'ahmed sub category',
      nameAr: 'ahmed sub category',
      color: 'primary',
      companyId: 29,
      sequence: 131,
      branchCompanyCategories: [
        {
          id: 475,
          companyCategoryId: 1119,
          companyBranchId: 1113,
          active: true,
        },
      ],
    },
    {
      id: 1120,
      name: 'Ahmed test 2',
      nameAr: 'Ahmed test 2',
      color: 'primary',
      companyId: 29,
      sequence: 132,
      branchCompanyCategories: [
        {
          id: 476,
          companyCategoryId: 1120,
          companyBranchId: 1113,
          active: true,
        },
      ],
    },
    {
      id: 1121,
      name: 'Jazzar',
      nameAr: 'جزار',
      color: 'primary',
      companyId: 29,
      sequence: 133,
      branchCompanyCategories: [
        {
          id: 477,
          companyCategoryId: 1121,
          companyBranchId: 1113,
          active: true,
        },
      ],
    },
    {
      id: 1122,
      name: 'Toot-توت',
      nameAr: 'Toot-توت',
      color: 'primary',
      companyId: 29,
      sequence: 134,
      branchCompanyCategories: [
        {
          id: 478,
          companyCategoryId: 1122,
          companyBranchId: 35,
          active: false,
        },
        {
          id: 479,
          companyCategoryId: 1122,
          companyBranchId: 36,
          active: false,
        },
        {
          id: 480,
          companyCategoryId: 1122,
          companyBranchId: 1037,
          active: false,
        },
        {
          id: 481,
          companyCategoryId: 1122,
          companyBranchId: 1043,
          active: false,
        },
        {
          id: 482,
          companyCategoryId: 1122,
          companyBranchId: 1044,
          active: false,
        },
        {
          id: 483,
          companyCategoryId: 1122,
          companyBranchId: 1064,
          active: false,
        },
        {
          id: 484,
          companyCategoryId: 1122,
          companyBranchId: 1065,
          active: false,
        },
        {
          id: 485,
          companyCategoryId: 1122,
          companyBranchId: 1066,
          active: false,
        },
        {
          id: 486,
          companyCategoryId: 1122,
          companyBranchId: 1067,
          active: false,
        },
        {
          id: 487,
          companyCategoryId: 1122,
          companyBranchId: 1073,
          active: false,
        },
        {
          id: 488,
          companyCategoryId: 1122,
          companyBranchId: 1078,
          active: false,
        },
        {
          id: 489,
          companyCategoryId: 1122,
          companyBranchId: 1113,
          active: true,
        },
        {
          id: 518,
          companyCategoryId: 1122,
          companyBranchId: 1119,
          active: true,
        },
      ],
    },
    {
      id: 1123,
      name: 'Perfumes',
      nameAr: 'Perfumes',
      color: 'primary',
      companyId: 29,
      sequence: 135,
      branchCompanyCategories: [
        {
          id: 490,
          companyCategoryId: 1123,
          companyBranchId: 35,
          active: false,
        },
        {
          id: 491,
          companyCategoryId: 1123,
          companyBranchId: 36,
          active: true,
        },
        {
          id: 492,
          companyCategoryId: 1123,
          companyBranchId: 1037,
          active: false,
        },
        {
          id: 493,
          companyCategoryId: 1123,
          companyBranchId: 1043,
          active: false,
        },
        {
          id: 494,
          companyCategoryId: 1123,
          companyBranchId: 1044,
          active: false,
        },
        {
          id: 495,
          companyCategoryId: 1123,
          companyBranchId: 1064,
          active: false,
        },
        {
          id: 496,
          companyCategoryId: 1123,
          companyBranchId: 1065,
          active: false,
        },
        {
          id: 497,
          companyCategoryId: 1123,
          companyBranchId: 1066,
          active: false,
        },
        {
          id: 498,
          companyCategoryId: 1123,
          companyBranchId: 1067,
          active: false,
        },
        {
          id: 499,
          companyCategoryId: 1123,
          companyBranchId: 1073,
          active: false,
        },
        {
          id: 500,
          companyCategoryId: 1123,
          companyBranchId: 1078,
          active: false,
        },
        {
          id: 501,
          companyCategoryId: 1123,
          companyBranchId: 1113,
          active: false,
        },
      ],
    },
    {
      id: 1124,
      name: 'حلويات صحية',
      nameAr: 'حلويات صحية',
      color: 'primary',
      companyId: 29,
      sequence: 136,
      branchCompanyCategories: [
        {
          id: 502,
          companyCategoryId: 1124,
          companyBranchId: 1113,
          active: true,
        },
      ],
    },
    {
      id: 1126,
      name: 'Palestine ',
      nameAr: 'فلسطين',
      color: 'danger',
      companyId: 29,
      sequence: 136,
      branchCompanyCategories: [
        {
          id: 519,
          companyCategoryId: 1126,
          companyBranchId: 35,
          active: false,
        },
        {
          id: 520,
          companyCategoryId: 1126,
          companyBranchId: 36,
          active: true,
        },
        {
          id: 521,
          companyCategoryId: 1126,
          companyBranchId: 1037,
          active: false,
        },
        {
          id: 522,
          companyCategoryId: 1126,
          companyBranchId: 1043,
          active: false,
        },
        {
          id: 523,
          companyCategoryId: 1126,
          companyBranchId: 1044,
          active: false,
        },
        {
          id: 524,
          companyCategoryId: 1126,
          companyBranchId: 1064,
          active: false,
        },
        {
          id: 525,
          companyCategoryId: 1126,
          companyBranchId: 1065,
          active: false,
        },
        {
          id: 526,
          companyCategoryId: 1126,
          companyBranchId: 1066,
          active: false,
        },
        {
          id: 527,
          companyCategoryId: 1126,
          companyBranchId: 1067,
          active: false,
        },
        {
          id: 528,
          companyCategoryId: 1126,
          companyBranchId: 1073,
          active: false,
        },
        {
          id: 529,
          companyCategoryId: 1126,
          companyBranchId: 1078,
          active: false,
        },
        {
          id: 530,
          companyCategoryId: 1126,
          companyBranchId: 1113,
          active: false,
        },
        {
          id: 531,
          companyCategoryId: 1126,
          companyBranchId: 1119,
          active: false,
        },
      ],
    },
    {
      id: 1125,
      name: 'Dried Fruits',
      nameAr: 'Dried Fruits',
      color: 'primary',
      companyId: 29,
      sequence: 137,
      branchCompanyCategories: [
        {
          id: 505,
          companyCategoryId: 1125,
          companyBranchId: 35,
          active: false,
        },
        {
          id: 506,
          companyCategoryId: 1125,
          companyBranchId: 36,
          active: false,
        },
        {
          id: 507,
          companyCategoryId: 1125,
          companyBranchId: 1037,
          active: false,
        },
        {
          id: 508,
          companyCategoryId: 1125,
          companyBranchId: 1043,
          active: false,
        },
        {
          id: 509,
          companyCategoryId: 1125,
          companyBranchId: 1044,
          active: false,
        },
        {
          id: 510,
          companyCategoryId: 1125,
          companyBranchId: 1064,
          active: false,
        },
        {
          id: 511,
          companyCategoryId: 1125,
          companyBranchId: 1065,
          active: false,
        },
        {
          id: 512,
          companyCategoryId: 1125,
          companyBranchId: 1066,
          active: false,
        },
        {
          id: 513,
          companyCategoryId: 1125,
          companyBranchId: 1067,
          active: false,
        },
        {
          id: 514,
          companyCategoryId: 1125,
          companyBranchId: 1073,
          active: false,
        },
        {
          id: 515,
          companyCategoryId: 1125,
          companyBranchId: 1078,
          active: false,
        },
        {
          id: 516,
          companyCategoryId: 1125,
          companyBranchId: 1113,
          active: true,
        },
        {
          id: 517,
          companyCategoryId: 1125,
          companyBranchId: 1119,
          active: true,
        },
      ],
    },
  ],
  meta: null,
};
